### ISSUE TITLE
does this still work and ban rate%?

### ISSUE THREAD

**Issue by TherFdurdv32** [Trenied-12/Valorant-Triggerbot#1]
does this work for this update? and you got discord?

**Comment by Trenied-12** [comment]
Sure, it also works in this update and will continue to work as long as Valorant doesn't change anything big in the near future. And yes, I have discord. I am of the opinion that you can not be banned by this Trigger Aim Bot.

**Comment by TherFdurdv32** [comment]
send your discord

**Comment by Trenied-12** [comment]
My Discord: Trenied#5577

**Comment by TherFdurdv32** [comment]
sented
