### ISSUE TITLE
If you create your own colors and make a selection, for some reason it will be selected as a weapon.

### ISSUE THREAD

**Issue by eito0504** [Trenied-12/Valorant-Triggerbot#5]
Hello. I am Japanese. I am using a translator, so my sentences may be a little strange. The default triggerbot color vision setting has too wide a range of recognition and shoots everywhere. So I created my own colors based on the web page. After creating it, when I select it, for some reason the color is applied to the weapon selection item. The triggerbot does not respond either.

**Comment by Trenied-12** [comment]
Unfortunately, I don't quite know what you mean, or where a problem might be. If the problem persists Please define me more precisely what you have done and where the problem is exactly.
